#!/bin/bash

# https://github.com/ThePolishHussar/HussarInstaller/
# Matrix - @thewingedhussar:matrix.org

scriptmod () {

	BTEXTRA=''

	echo 'Default packages: bluex, bluez-utils'
	read -p 'Install extra packages? [y/N] ' YN
	case $YN in 
	 	[Yy]* ) MANUAL="true";;
		* ) MANUAL="false";;
	esac

	if [ "$MANUAL" == "true" ]; then

		echo 'Enter packages. Type "done" when finished'
		while true; do
			read -p "Package name: " PKG
			case $PKG in 
				done) break;;
				*) 	BTEXTRA=(
						$( [ ! -z "$BTEXTRA" ] && echo "${BTEXTRA[@]}")
						"$PKG"	
					)
				;;
			esac
		done
	fi
	
	{
	echo 'BTEXTRA=('
	for PKG in "${BTEXTRA[@]}"; do
		echo $PKG 
	done
	echo ')'
	} > ./modules/bluetooth.conf
}

[ -f ./modules/bluetooth.conf ] && source ./modules/bluetooth.conf
packages=(
	bluez
	bluez-utils
	"${BTEXTRA[@]}"
)


postconfig () {
	systemctl enable bluetooth.service
}
