#!/bin/bash

# https://github.com/ThePolishHussar/HussarInstaller
# Matrix - @thewingedhussar:matrix.org

scriptmod () {
	 #if [ -f ./modules/desktop.conf ]; then
		 #cat ./modules/desktop.conf
		 #while true; do
			 #read -p "Use these settings? [Y/n] " yn
			 #case $yn in
				 #[Nn]* ) break;;
				 #* ) exit;;
			 #esac
		 #done
	 #fi	
	PS3='Selection > '
	xorg=(
		xserver	
	)		
	wayland=(
		waylandserver
	)
	select DISPLAY_SERVER in xorg wayland; do break; done	
	declare -n DISPLAY_SERVER=$DISPLAY_SERVER
	desktop_enviorments=(
		manual
	)
	select DESKTOP_ENVIORMENT in "${desktop_enviorments[@]}"; do break; done	
	if [ "$DESKTOP_ENVIORMENT" == "manual" ]; then
		DESKTOP_ENVIORMENT=''
		echo 'Manually List Packages'
		echo "enter 'done' at anytime to end you list"
		while true; do
			read -p "new package: " pkg
			case $pkg in
				done) break;;
				*)	DESKTOP_ENVIORMENT=( ${DESKTOP_ENVIORMENT[@]} "$pkg" )
				;;
			esac
		done
	else
		declare -n DESKTOP_ENVIORMENT=$DESKTOP_ENVIORMENT
	fi
	AURlogins=(
	ly
	)
	logins=(
	sddm
	lightdm
	gdm
	"${AURlogins[@]}"
	)
	select DISPLAY_MANAGER in "${logins[@]}"; do break; done
	for aur in "${AURlogins[@]}"; do
		[ "$aur" == "$DISPLAY_MANAGER" ] && DISPLAY_MANAGER='' && AUR_DISPLAY_MANAGER="$aur"
	done
	[ -f ./modules/desktop.conf ] && rm ./modules/desktop.conf
	echo 'DISPLAY_SERVER=(' >> ./modules/desktop.conf
	for PKG in "${DISPLAY_SERVER[@]}"; do	
		echo "$PKG" >> ./modules/desktop.conf
	done
	echo ')' >> ./modules/desktop.conf

	echo 'DESKTOP_ENVIORMENT=(' >> ./modules/desktop.conf
	for PKG in "${DESKTOP_ENVIORMENT[@]}"; do	
		echo "$PKG" >> ./modules/desktop.conf
	done
	echo ')' >> ./modules/desktop.conf

	if [ ! -z "$DISPLAY_MANAGER" ]; then
		echo 'DISPLAY_MANAGER=(' >> ./modules/desktop.conf
		for PKG in "${DISPLAY_MANAGER[@]}"; do	
			echo "$PKG" >> ./modules/desktop.conf
		done
	elif [ ! -z "$AUR_DISPLAY_MANAGER" ]; then
		echo 'AUR_DISPLAY_MANAGER=(' >> ./modules/desktop.conf
		for PKG in "${AUR_DISPLAY_MANAGER[@]}"; do	
			echo "$PKG" >> ./modules/desktop.conf
		done
	fi
	echo ')' >> ./modules/desktop.conf
}


user () {
	source ./modules/desktop.conf
	packages=(
		"${DISPLAY_SERVER[@]}"
		"${DESKTOP_ENVIORMENT[@]}"
		"${DISPLAY_MANAGER[@]}"
	)	
	AURpackages=(
		"${AUR_DISPLAY_MANAGER[@]}"
	)
}

postconfig () {
	source ./modules/desktop.conf
	[ ! -z ${DISPLAY_MANAGER} ] && systemctl enable ${DISPLAY_MANAGER}.serivce
	[ ! -z ${AUR_DISPLAY_MANAGER} ] && systemctl enable ${AUR_DISPLAY_MANAGER}.service
}
