#!/bin/bash

# https://github.com/ThePolishHussar/HussarInstaller/
# Matrix - @thewingedhussar:matrix.org

scriptmod () {    
	{
	echo 'No Applicable Settings'
	} > ./modules/printing.conf
}


baseconfig () {
	usermod -a -G lp $USERNAME
}

packages=(
	cups 
	gutenprint
	foomatic-db-gutenprint-ppds
)

postconfig () {
	systemctl enable cups.service
}

finalmsg () {
	echo 'You still need to add the printer manually. 
Run "sudo pacman -S system-config-printer" for an GUI to easyly setup
If drivers are still missing consult https://wiki.archlinux.org/title/CUPS/Printer-specific_problems.
Also note this from the arch wiki [https://wiki.archlinux.org/title/CUPS]
"Note: When the Gutenprint packages get updated, the printers using Gutenprint drivers will stop working until you run cups-genppdupdate as root and restart CUPS. cups-genppdupdate will update the PPD files of the configured printers, see cups-genppdupdate(8) for more details."
'
}
